services:
  app:
    build:
      context: .
      dockerfile: cmd/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      broker:
        condition: service_healthy


  broker:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  codeprocessor:
    build:
      context: .
      dockerfile: cmd/codeProcessor/Dockerfile
    depends_on:
      app:
        condition: service_started
      broker:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
