global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'codeprocessor'
    static_configs:
      - targets: ['codeprocessor:9091']

  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']